name: Feature request
description: Suggest a raceGPS feature
title: "[Feature]: "
labels: ["feature"]
body:
  - type: textarea
    id: feature
    attributes:
      label: Feature
    validations:
      required: true
